routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\ImageUploadController;
use App\Http\Controllers\ProductController;
use App\Http\Middleware\CheckRole;
use App\Http\Middleware\Admin;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('homepage');
});
Route::get('/login', function () {
    return view('login');
});
Route::get('/register', function () {
    return view('register');
});



Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/', [ProductController::class, 'homepage']); 
 

Route::middleware([CheckRole::class])->group(function(){
    Route::get('/update', [App\Http\Controllers\HomeController::class, 'update'])->name('update');
    Route::post('/edits', [App\Http\Controllers\UserController::class, 'edits'])->name('edits');
    Route::get('/shop/{id}', [ProductController::class, 'shop']);

 });
 Route::middleware([Admin::class])->group(function(){
    Route::post('/edits', [App\Http\Controllers\UserController::class, 'edits'])->name('edits');
    Route::get('/list', [App\Http\Controllers\UserController::class, 'show'])->name('list');
    Route::resource('products', 'App\Http\Controllers\ProductController');   
    Route::resource('products.create', ProductController::class); 
    Route::resource('products.updateproduct', ProductController::class); 
    Route::get('/products/updates/{id}', [ProductController::class, 'updates']);
    Route::get('/products/edit_product/{id}', [ProductController::class, 'edit']); 
    Route::get('memberupdate/{id}', [App\Http\Controllers\UserController::class, 'memberupdate'])->name('memberupdate');
    Route::get('delete/{id}', [App\Http\Controllers\UserController::class, 'delete'])->name('delete');
    Route::get('listed', [App\Http\Controllers\MemberController::class, 'listed'])->name('listed'); 
    Route::post('/updateproduct', [App\Http\Controllers\UserController::class, 'updateproduct'])->name('updateproduct'); 
    Route::get('/dashboard', function () {return view('dashboard/index');}); 
    
    Route::get('/dashboard', [App\Http\Controllers\UserController::class, 'show'])->name('dashboard');

});

resources/views/dashboard/content.blade.php
@extends('index')

@section('content')
<div class="uk-section-small">
                <div class="uk-container uk-container-large">
                    <div uk-grid class="uk-child-width-1-1@s uk-child-width-1-2@m uk-child-width-1-4@xl">
                        <div>
                            <div class="uk-card uk-card-default uk-card-body">
                                <span class="statistics-text">New Registrations</span><br />
                                <span class="statistics-number">
                                    14.164
                                    <span class="uk-label uk-label-success">
                                        8% <span class="ion-arrow-up-c"></span>
                                    </span>
                                </span>
                            </div>
                        </div>
                        <div>
                            <div class="uk-card uk-card-default uk-card-body">
                                <span class="statistics-text">Website Traffic</span><br />
                                <span class="statistics-number">
                                    123.238
                                    <span class="uk-label uk-label-danger">
                                        13% <span class="ion-arrow-down-c"></span>
                                    </span>
                                </span>
                            </div>
                        </div>
                        <div>
                            <div class="uk-card uk-card-default uk-card-body">
                                <span class="statistics-text">Total Invoices</span><br />
                                <span class="statistics-number">
                                    2.316
                                    <span class="uk-label uk-label-success">
                                        37% <span class="ion-arrow-up-c"></span>
                                    </span>
                                </span>
                            </div>
                        </div>
                        <div>
                            <div class="uk-card uk-card-default uk-card-body">
                                <span class="statistics-text">Total Income</span><br />
                                <span class="statistics-number">
                                    6.384€
                                    <span class="uk-label uk-label-success">
                                        26% <span class="ion-arrow-up-c"></span>
                                    </span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div uk-grid class="uk-child-width-1-1@s uk-child-width-1-2@l">
                        <div>
                            <div class="uk-card uk-card-default">
                                <div class="uk-card-header">
                                    Website Traffic
                                </div>
                                <div class="uk-card-body">
                                    <canvas id="chart1"></canvas>
                                </div>
                            </div>
                        </div>
                        <div>
                            <div class="uk-card uk-card-default">
                                <div class="uk-card-header">
                                    Website Traffic
                                </div>
                                <div class="uk-card-body">
                                    <canvas id="chart2"></canvas>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

    @endsection

resources/views/dashboard/create.blade.php
@extends('layouts.apps')

@section('content')
@if ($errors->any())
   <div class="alert alert-danger">
     <ul>
     @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
     @endforeach
     </ul>
   </div>
@endif
<div class="uk-child-width-expand@s uk-text-center" uk-grid>
    <div>
        <div class=""></div>
    </div>
    <div>
        <div class="">
<div class="uk-card uk-card-default">
                                <div class="uk-card-header">
                                    Add Product
                                </div>
                                <div class="uk-card-body"> 
                                        <form action="{{ route('products.store') }}" method="post" enctype="multipart/form-data">
                                        <!-- Add CSRF Token -->
                                        @csrf
                                        <fieldset class="uk-fieldset">

                                        <div class="uk-margin"> 
                                        <div class="uk-form-controls">
                                            <input class="uk-input" id="form-stacked-text" type="text" name="name" placeholder="Product Name" required>
                                            </div>
                                        </div> 

                                        <div class="uk-margin"> 
                                        <div class="uk-form-controls">
                                            <input class="uk-input" id="form-stacked-text" type="number" name="price" placeholder="Product Price" required>
                                            </div>
                                        </div>

                                        <div class="uk-margin">
                                            <textarea class="uk-textarea" rows="5" name="description" placeholder="Description" required></textarea>
                                        </div>
 

                                        <div class="uk-margin">
                                            <div uk-form-custom>
                                            <input type="file" name="file" required>
                                            <button class="uk-button uk-button-default" type="button" tabindex="-1">Select Photo</button>
                                            </div>
                                            </div>

                                            <div class="uk-margin">
                                            <button type="submit" class="uk-button uk-button-primary">
                                            Submit
                                            </button>
                                             <a href="/products" class="uk-button uk-button-danger">
                                            Cancel
                                            </a>
                                            </div>

                                            </fieldset>
                                            </form>
                                            </div>
                                            </div>
                                            </div>
    </div>
    <div>
        <div class=""></div>
    </div>
</div> 
@endsection

resources/views/dashboard/customerlist.blade.php
@extends('layouts.apps')

@section('content')
<div class="uk-card uk-card-default">
                                <div class="uk-card-header">
                                    Customer List
                                </div>
                                <div class="uk-card-body">
                                    <table class="uk-table uk-table-striped">
                                        <thead>
                                            <tr> 
                                                <th scope="col">#</th>
                                                <th scope="col">Name</th> 
                                                <th scope="col">Email</th>
                                                <th scope="col">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
@foreach($members as $count=> $user) 
    <tr>
      <th scope="row">{{++$count}}</th> 
      <td>{{$user['name']}}</td>
      <td>{{$user['email']}}</td>
      <td>
      <a href={{"memberupdate/".$user['id']}}>Edit</a>
      <a href={{"delete/".$user['id']}}>Delete</a>
      </td>
    </tr> 
@endforeach
                                           
                                        </tbody>
                                    </table>
                                </div>
                            </div>

@endsection

resources/views/dashboard/edit_product.blade.php
@extends('layouts.apps')

@section('content')
@if ($errors->any())
   <div class="alert alert-danger">
     <ul>
     @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
     @endforeach
     </ul>
   </div>
@endif
<div class="uk-child-width-expand@s uk-text-center" uk-grid>
    <div>
        <div class=""></div>
    </div>
    <div>
        <div class="">
<div class="uk-card uk-card-default">
                                <div class="uk-card-header">
                                    Add Product
                                </div>
                                <div class="uk-card-body"> 
                                        <form action="{{ route('updateproduct') }}" method="post" enctype="multipart/form-data">
                                        <!-- Add CSRF Token -->
                                        @csrf
                                        <fieldset class="uk-fieldset">

                                        <div class="uk-margin"> 
                                        <div class="uk-form-controls">
                                            <input name="id" type="hidden" value="{{ $data['id'] }}"/>
                                            <input class="uk-input" id="form-stacked-text" type="text" name="name" placeholder="Product Name" value="{{ $data['name'] }}" required>
                                            </div>
                                        </div> 

                                        <div class="uk-margin"> 
                                        <div class="uk-form-controls">
                                            <input class="uk-input" id="form-stacked-text" type="number" name="price" placeholder="Product Price" value="{{ $data['price'] }}" required>
                                            </div>
                                        </div>

                                        <div class="uk-margin">
                                            <textarea class="uk-textarea" rows="5" name="description" placeholder="Description" required>{{ $data['description'] }}</textarea>
                                        </div>
 

                                        <div class="uk-margin">
                                            <div uk-form-custom>
                                            <input type="file" name="file" required>
                                            <button class="uk-button uk-button-default" type="button" tabindex="-1">Select Photo</button>
                                            </div>
                                            </div>

                                            <div class="uk-margin">
                                            <button type="submit" class="uk-button uk-button-primary">
                                            Update
                                            </button>

                                            <a href="/products" class="uk-button uk-button-danger">
                                            Cancel
                                            </a>
                                            </div>


                                            </fieldset>
                                            </form>
                                            </div>
                                            </div>
                                            </div>
    </div>
    <div>
        <div class=""></div>
    </div>
</div> 
@endsection

resources/views/dashboard/navbar.blade.php
@extends('index')

@section('sidebar')
    @parent 
<div uk-sticky class="uk-navbar-container tm-navbar-container uk-active">
            <div class="uk-container uk-container-expand">
                <nav uk-navbar>
                    <div class="uk-navbar-left">
                        <a id="sidebar_toggle" class="uk-navbar-toggle" uk-navbar-toggle-icon ></a>
                        <a href="#" class="uk-navbar-item uk-logo">
                            UI Admin
                        </a>
                    </div>
                    <div class="uk-navbar-right uk-light">
                        <ul class="uk-navbar-nav">
                            <li class="uk-active">
                                <a href="#">Èrik &nbsp;<span class="ion-ios-arrow-down"></span></a>
                                <div uk-dropdown="pos: bottom-right; mode: click; offset: -17;">
                                   <ul class="uk-nav uk-navbar-dropdown-nav">
                                       <li class="uk-nav-header">Options</li>
                                       <li><a href="#">Edit Profile</a></li>
                                       <li class="uk-nav-header">Actions</li>
                                       <li><a href="#">Lock</a></li>
                                       <li><a href="#">Logout</a></li>
                                   </ul>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    @endsection

resources/views/dashboard/productlist.blade.php
@extends('layouts.apps')

@section('content')
<div class="uk-card uk-card-default">
                                <div class="uk-card-header">
                                    Product List
                                    <button class="uk-button uk-button-primary">Add Product</button>
                                </div>
                                <div class="uk-card-body">
                                    <table class="uk-table uk-table-striped">
                                        <thead>
                                            <tr> 
                                                <th scope="col">#</th>
                                                <th scope="col">Name</th> 
                                                <th scope="col">Product Price</th> 
                                                <th scope="col">Description</th>
                                                <th scope="col">Photo</th>
                                                <th scope="col">Action</th> 
                                            </tr>
                                        </thead>
                                        <tbody>
@foreach($product as $count=> $products) 
    <tr>
      <th scope="row">{{++$count}}</th> 
      <td>{{$products['name']}}</td>
      <td>{{$products['price']}}</td>
      <td>{{$products['description']}}</td>
      <td><img src="{{asset('/storage/product/' . $products->file_path)}}" class="img-thumbnail" alt="Responsive image"></td>
      <td> 
      <a href={{"/products/edit_product/".$products['id']}}>Edit</a>
      <a href={{"/products/updates/".$products['id']}}>Delete</a>
      </td>
    </tr> 
@endforeach 
                                           
                                        </tbody>
                                    </table>
                                </div>
                            </div>

@endsection